{{- if .Values.controller.serviceAccount.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "typhoon.webhook.fullname" . }}
  labels:
    {{- include "typhoon.webhook.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "typhoon.webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typhoon-webhook

{{- end }}