apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typhoon.webhook.fullname" . }}-certs
  labels:
    {{- include "typhoon.webhook.labels" . | nindent 4 }}
# The data is populated at install time.