apiVersion: v1
kind: Service
metadata:
  name: {{ include "typhoon.webhook.fullname" . }}
  labels:
    {{- include "typhoon.webhook.labels" . | nindent 4 }}
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    {{- include "typhoon.webhook.selectorLabels" . | nindent 4 }}