---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  accounting.conf:
