apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: demo-to-display
spec:
  broker: imc-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-success-capture
      namespace: default