---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          ports:
            - containerPort: 8080

---

apiVersion: flow.typhoon.zeiss.com/v1alpha1
kind: XMLToJSONTransformation
metadata:
  name: demo
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: default

---

apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: xml-transformation-demo
spec:
  schedule: "*/1 * * * *"
  contentType: application/xml
  data: '<locations><location><name>Dallas</name><id>11111</id></location><location><name>Frisco</name><id>22222</id></location><location><name>Rockwall</name><id>33333</id></location></locations>'
  sink:
    ref:
      apiVersion: flow.typhoon.zeiss.com/v1alpha1
      kind: XMLToJSONTransformation
      name: demo