config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi

  resolver:
    enabled: true
    merge:
      type: full
      interval: "2m"
      timeout: "1.9s"

  gateway:
    enabled: true
    merge:
      gateways:
        - name: "nats"
          port: 4222
          authorization:
            timeout: 3
            user: gwp
            password: gwp
      authorization:
        timeout: 3
        user: gwp
        password: gwp

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-ipv4: ""
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      type: LoadBalancer

container:
  env:
    # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # should be ~90% of memory limit
    GOMEMLIMIT: 7GiB
  merge:
    # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "2"
        memory: 8Gi
