config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi

  gateway:
    enabled: true
    merge:
      gateways:
        - name: typhoon-gw-west-nats
          urls:
            - nats://gwp:gwp@10.210.95.239:7222
        - name: typhoon-gw-central-nats
          urls:
            - nats://gwp:gwp@10.27.57.135:7222
      authorization:
        user: gwp
        password: gwp

  merge:
    accounts:
      $SYS:
        jetstream: true
        users:
          - user: sys
            password: pass

natsBox:
  contexts:
    sys:
      merge: { user: sys, password: pass }
  defaultContextName: sys

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-ipv4: ""
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      type: LoadBalancer

container:
  env:
    # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # should be ~90% of memory limit
    GOMEMLIMIT: 7GiB
  merge:
    # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "2"
        memory: 8Gi
