package v1alpha1

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime/schema"

	"knative.dev/pkg/apis"
	duckv1 "knative.dev/pkg/apis/duck/v1"

	"github.com/zeiss/typhoon/pkg/apis/common/v1alpha1"
)

// GetGroupVersionKind implements kmeta.OwnerRefable.
func (s *AzureQueueStorageSource) GetGroupVersionKind() schema.GroupVersionKind {
	return SchemeGroupVersion.WithKind("AzureQueueStorageSource")
}

// GetConditionSet implements duckv1.KRShaped.
func (s *AzureQueueStorageSource) GetConditionSet() apis.ConditionSet {
	return v1alpha1.EventSenderConditionSet
}

// GetStatus implements duckv1.KRShaped.
func (s *AzureQueueStorageSource) GetStatus() *duckv1.Status {
	return &s.Status.Status
}

// GetSink implements EventSender.
func (s *AzureQueueStorageSource) GetSink() *duckv1.Destination {
	return &s.Spec.Sink
}

// GetStatusManager implements Reconcilable.
func (s *AzureQueueStorageSource) GetStatusManager() *v1alpha1.StatusManager {
	return &v1alpha1.StatusManager{
		ConditionSet: s.GetConditionSet(),
		Status:       &s.Status,
	}
}

// AsEventSource implements EventSource.
func (s *AzureQueueStorageSource) AsEventSource() string {
	return AzureQueueStorageSourceName(s.Namespace, s.Name)
}

// AzureQueueStorageSourceName returns a unique reference to the source suitable for use
// as as a CloudEvent source.
func AzureQueueStorageSourceName(namespace, name string) string {
	return "com.zeiss.azure/" + namespace + "/" + name
}

// Supported event types
const (
	AzureQueueStorageEventType = "com.microsoft.azure.queuestorage"
)

// GetEventTypes returns the event types generated by the source.
func (s *AzureQueueStorageSource) GetEventTypes() []string {
	return []string{AzureQueueStorageEventType}
}

// GetAdapterOverrides implements AdapterConfigurable.
func (s *AzureQueueStorageSource) GetAdapterOverrides() *v1alpha1.AdapterOverrides {
	return s.Spec.AdapterOverrides
}

// SetDefaults implements apis.Defaultable
func (s *AzureQueueStorageSource) SetDefaults(ctx context.Context) {
}

// Validate implements apis.Validatable
func (s *AzureQueueStorageSource) Validate(ctx context.Context) *apis.FieldError {
	return nil
}
