package v1alpha1

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime/schema"

	"knative.dev/pkg/apis"
	duckv1 "knative.dev/pkg/apis/duck/v1"

	"github.com/zeiss/typhoon/pkg/apis/common/v1alpha1"
)

// GetGroupVersionKind implements kmeta.OwnerRefable.
func (s *SalesforceSource) GetGroupVersionKind() schema.GroupVersionKind {
	return SchemeGroupVersion.WithKind("SalesforceSource")
}

// GetConditionSet implements duckv1.KRShaped.
func (s *SalesforceSource) GetConditionSet() apis.ConditionSet {
	return v1alpha1.EventSenderConditionSet
}

// GetStatus implements duckv1.KRShaped.
func (s *SalesforceSource) GetStatus() *duckv1.Status {
	return &s.Status.Status
}

// GetSink implements EventSender.
func (s *SalesforceSource) GetSink() *duckv1.Destination {
	return &s.Spec.Sink
}

// GetStatusManager implements Reconcilable.
func (s *SalesforceSource) GetStatusManager() *v1alpha1.StatusManager {
	return &v1alpha1.StatusManager{
		ConditionSet: s.GetConditionSet(),
		Status:       &s.Status,
	}
}

// AsEventSource implements EventSource.
func (s *SalesforceSource) AsEventSource() string {
	channel := s.Spec.Subscription.Channel
	if channel[0] != '/' {
		channel = "/" + channel
	}
	return "com.zeiss.salesforce" + channel
}

// GetEventTypes returns the event types generated by the source.
func (s *SalesforceSource) GetEventTypes() []string {
	return []string{"com.salesforce.stream.message"}
}

// GetAdapterOverrides implements AdapterConfigurable.
func (s *SalesforceSource) GetAdapterOverrides() *v1alpha1.AdapterOverrides {
	return s.Spec.AdapterOverrides
}

// SetDefaults implements apis.Defaultable
func (s *SalesforceSource) SetDefaults(ctx context.Context) {
}

// Validate implements apis.Validatable
func (s *SalesforceSource) Validate(ctx context.Context) *apis.FieldError {
	return nil
}
