//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/zeiss/typhoon/pkg/apis/common/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuth) DeepCopyInto(out *AzureAuth) {
	*out = *in
	if in.ServicePrincipal != nil {
		in, out := &in.ServicePrincipal, &out.ServicePrincipal
		*out = new(AzureServicePrincipal)
		(*in).DeepCopyInto(*out)
	}
	if in.SASToken != nil {
		in, out := &in.SASToken, &out.SASToken
		*out = new(AzureSASToken)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuth.
func (in *AzureAuth) DeepCopy() *AzureAuth {
	if in == nil {
		return nil
	}
	out := new(AzureAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureResourceID) DeepCopyInto(out *AzureResourceID) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureResourceID.
func (in *AzureResourceID) DeepCopy() *AzureResourceID {
	if in == nil {
		return nil
	}
	out := new(AzureResourceID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSASToken) DeepCopyInto(out *AzureSASToken) {
	*out = *in
	in.KeyName.DeepCopyInto(&out.KeyName)
	in.KeyValue.DeepCopyInto(&out.KeyValue)
	in.ConnectionString.DeepCopyInto(&out.ConnectionString)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSASToken.
func (in *AzureSASToken) DeepCopy() *AzureSASToken {
	if in == nil {
		return nil
	}
	out := new(AzureSASToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusQueueSource) DeepCopyInto(out *AzureServiceBusQueueSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusQueueSource.
func (in *AzureServiceBusQueueSource) DeepCopy() *AzureServiceBusQueueSource {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusQueueSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusQueueSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusQueueSourceList) DeepCopyInto(out *AzureServiceBusQueueSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureServiceBusQueueSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusQueueSourceList.
func (in *AzureServiceBusQueueSourceList) DeepCopy() *AzureServiceBusQueueSourceList {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusQueueSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusQueueSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusQueueSourceSpec) DeepCopyInto(out *AzureServiceBusQueueSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	out.QueueID = in.QueueID
	in.Auth.DeepCopyInto(&out.Auth)
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusQueueSourceSpec.
func (in *AzureServiceBusQueueSourceSpec) DeepCopy() *AzureServiceBusQueueSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusQueueSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusSource) DeepCopyInto(out *AzureServiceBusSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusSource.
func (in *AzureServiceBusSource) DeepCopy() *AzureServiceBusSource {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusSourceList) DeepCopyInto(out *AzureServiceBusSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureServiceBusSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusSourceList.
func (in *AzureServiceBusSourceList) DeepCopy() *AzureServiceBusSourceList {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusSourceSpec) DeepCopyInto(out *AzureServiceBusSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	if in.TopicID != nil {
		in, out := &in.TopicID, &out.TopicID
		*out = new(AzureResourceID)
		**out = **in
	}
	if in.QueueID != nil {
		in, out := &in.QueueID, &out.QueueID
		*out = new(AzureResourceID)
		**out = **in
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.WebSocketsEnable != nil {
		in, out := &in.WebSocketsEnable, &out.WebSocketsEnable
		*out = new(bool)
		**out = **in
	}
	if in.MaxConcurrent != nil {
		in, out := &in.MaxConcurrent, &out.MaxConcurrent
		*out = new(int)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusSourceSpec.
func (in *AzureServiceBusSourceSpec) DeepCopy() *AzureServiceBusSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusSourceStatus) DeepCopyInto(out *AzureServiceBusSourceStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(AzureResourceID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusSourceStatus.
func (in *AzureServiceBusSourceStatus) DeepCopy() *AzureServiceBusSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusTopicSource) DeepCopyInto(out *AzureServiceBusTopicSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusTopicSource.
func (in *AzureServiceBusTopicSource) DeepCopy() *AzureServiceBusTopicSource {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusTopicSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusTopicSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusTopicSourceList) DeepCopyInto(out *AzureServiceBusTopicSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureServiceBusTopicSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusTopicSourceList.
func (in *AzureServiceBusTopicSourceList) DeepCopy() *AzureServiceBusTopicSourceList {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusTopicSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureServiceBusTopicSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusTopicSourceSpec) DeepCopyInto(out *AzureServiceBusTopicSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	out.TopicID = in.TopicID
	in.Auth.DeepCopyInto(&out.Auth)
	if in.WebSocketsEnable != nil {
		in, out := &in.WebSocketsEnable, &out.WebSocketsEnable
		*out = new(bool)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusTopicSourceSpec.
func (in *AzureServiceBusTopicSourceSpec) DeepCopy() *AzureServiceBusTopicSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusTopicSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServiceBusTopicSourceStatus) DeepCopyInto(out *AzureServiceBusTopicSourceStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.SubscriptionID != nil {
		in, out := &in.SubscriptionID, &out.SubscriptionID
		*out = new(AzureResourceID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServiceBusTopicSourceStatus.
func (in *AzureServiceBusTopicSourceStatus) DeepCopy() *AzureServiceBusTopicSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AzureServiceBusTopicSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureServicePrincipal) DeepCopyInto(out *AzureServicePrincipal) {
	*out = *in
	in.TenantID.DeepCopyInto(&out.TenantID)
	in.ClientID.DeepCopyInto(&out.ClientID)
	in.ClientSecret.DeepCopyInto(&out.ClientSecret)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureServicePrincipal.
func (in *AzureServicePrincipal) DeepCopy() *AzureServicePrincipal {
	if in == nil {
		return nil
	}
	out := new(AzureServicePrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsSource) DeepCopyInto(out *CloudEventsSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsSource.
func (in *CloudEventsSource) DeepCopy() *CloudEventsSource {
	if in == nil {
		return nil
	}
	out := new(CloudEventsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventsSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsSourceList) DeepCopyInto(out *CloudEventsSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEventsSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsSourceList.
func (in *CloudEventsSourceList) DeepCopy() *CloudEventsSourceList {
	if in == nil {
		return nil
	}
	out := new(CloudEventsSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventsSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsSourceSpec) DeepCopyInto(out *CloudEventsSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(HTTPCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.RateLimiter != nil {
		in, out := &in.RateLimiter, &out.RateLimiter
		*out = new(RateLimiter)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsSourceSpec.
func (in *CloudEventsSourceSpec) DeepCopy() *CloudEventsSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEventsSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPBasicAuth) DeepCopyInto(out *HTTPBasicAuth) {
	*out = *in
	in.Password.DeepCopyInto(&out.Password)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPBasicAuth.
func (in *HTTPBasicAuth) DeepCopy() *HTTPBasicAuth {
	if in == nil {
		return nil
	}
	out := new(HTTPBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPCredentials) DeepCopyInto(out *HTTPCredentials) {
	*out = *in
	if in.BasicAuths != nil {
		in, out := &in.BasicAuths, &out.BasicAuths
		*out = make([]HTTPBasicAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPCredentials.
func (in *HTTPCredentials) DeepCopy() *HTTPCredentials {
	if in == nil {
		return nil
	}
	out := new(HTTPCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPollerSource) DeepCopyInto(out *HTTPPollerSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPollerSource.
func (in *HTTPPollerSource) DeepCopy() *HTTPPollerSource {
	if in == nil {
		return nil
	}
	out := new(HTTPPollerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPPollerSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPollerSourceList) DeepCopyInto(out *HTTPPollerSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPPollerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPollerSourceList.
func (in *HTTPPollerSourceList) DeepCopy() *HTTPPollerSourceList {
	if in == nil {
		return nil
	}
	out := new(HTTPPollerSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPPollerSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPollerSourceSpec) DeepCopyInto(out *HTTPPollerSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	if in.EventSource != nil {
		in, out := &in.EventSource, &out.EventSource
		*out = new(string)
		**out = **in
	}
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.CACertificate != nil {
		in, out := &in.CACertificate, &out.CACertificate
		*out = new(string)
		**out = **in
	}
	if in.BasicAuthUsername != nil {
		in, out := &in.BasicAuthUsername, &out.BasicAuthUsername
		*out = new(string)
		**out = **in
	}
	if in.BasicAuthPassword != nil {
		in, out := &in.BasicAuthPassword, &out.BasicAuthPassword
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPollerSourceSpec.
func (in *HTTPPollerSourceSpec) DeepCopy() *HTTPPollerSourceSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPPollerSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSource) DeepCopyInto(out *KafkaSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSource.
func (in *KafkaSource) DeepCopy() *KafkaSource {
	if in == nil {
		return nil
	}
	out := new(KafkaSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceAuth) DeepCopyInto(out *KafkaSourceAuth) {
	*out = *in
	if in.Kerberos != nil {
		in, out := &in.Kerberos, &out.Kerberos
		*out = new(KafkaSourceKerberos)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(KafkaSourceTLSAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSEnable != nil {
		in, out := &in.TLSEnable, &out.TLSEnable
		*out = new(bool)
		**out = **in
	}
	if in.SecurityMechanisms != nil {
		in, out := &in.SecurityMechanisms, &out.SecurityMechanisms
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceAuth.
func (in *KafkaSourceAuth) DeepCopy() *KafkaSourceAuth {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceKerberos) DeepCopyInto(out *KafkaSourceKerberos) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.ConfigPath != nil {
		in, out := &in.ConfigPath, &out.ConfigPath
		*out = new(string)
		**out = **in
	}
	if in.KeytabPath != nil {
		in, out := &in.KeytabPath, &out.KeytabPath
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.Keytab != nil {
		in, out := &in.Keytab, &out.Keytab
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceKerberos.
func (in *KafkaSourceKerberos) DeepCopy() *KafkaSourceKerberos {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceKerberos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceList) DeepCopyInto(out *KafkaSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceList.
func (in *KafkaSourceList) DeepCopy() *KafkaSourceList {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceSpec) DeepCopyInto(out *KafkaSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	if in.BootstrapServers != nil {
		in, out := &in.BootstrapServers, &out.BootstrapServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceSpec.
func (in *KafkaSourceSpec) DeepCopy() *KafkaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceTLSAuth) DeepCopyInto(out *KafkaSourceTLSAuth) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientCert != nil {
		in, out := &in.ClientCert, &out.ClientCert
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceTLSAuth.
func (in *KafkaSourceTLSAuth) DeepCopy() *KafkaSourceTLSAuth {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceTLSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMetrics) DeepCopyInto(out *OCIMetrics) {
	*out = *in
	if in.Compartment != nil {
		in, out := &in.Compartment, &out.Compartment
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetrics.
func (in *OCIMetrics) DeepCopy() *OCIMetrics {
	if in == nil {
		return nil
	}
	out := new(OCIMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in OCIMetricsDecodedList) DeepCopyInto(out *OCIMetricsDecodedList) {
	{
		in := &in
		*out = make(OCIMetricsDecodedList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetricsDecodedList.
func (in OCIMetricsDecodedList) DeepCopy() OCIMetricsDecodedList {
	if in == nil {
		return nil
	}
	out := new(OCIMetricsDecodedList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMetricsSource) DeepCopyInto(out *OCIMetricsSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetricsSource.
func (in *OCIMetricsSource) DeepCopy() *OCIMetricsSource {
	if in == nil {
		return nil
	}
	out := new(OCIMetricsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMetricsSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMetricsSourceList) DeepCopyInto(out *OCIMetricsSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIMetricsSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetricsSourceList.
func (in *OCIMetricsSourceList) DeepCopy() *OCIMetricsSourceList {
	if in == nil {
		return nil
	}
	out := new(OCIMetricsSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMetricsSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMetricsSourceSpec) DeepCopyInto(out *OCIMetricsSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	in.OracleAPIPrivateKey.DeepCopyInto(&out.OracleAPIPrivateKey)
	in.OracleAPIPrivateKeyPassphrase.DeepCopyInto(&out.OracleAPIPrivateKeyPassphrase)
	in.OracleAPIPrivateKeyFingerprint.DeepCopyInto(&out.OracleAPIPrivateKeyFingerprint)
	if in.PollingFrequency != nil {
		in, out := &in.PollingFrequency, &out.PollingFrequency
		*out = new(string)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]OCIMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetricsSourceSpec.
func (in *OCIMetricsSourceSpec) DeepCopy() *OCIMetricsSourceSpec {
	if in == nil {
		return nil
	}
	out := new(OCIMetricsSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiter) DeepCopyInto(out *RateLimiter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiter.
func (in *RateLimiter) DeepCopy() *RateLimiter {
	if in == nil {
		return nil
	}
	out := new(RateLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceAuth) DeepCopyInto(out *SalesforceAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceAuth.
func (in *SalesforceAuth) DeepCopy() *SalesforceAuth {
	if in == nil {
		return nil
	}
	out := new(SalesforceAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceSource) DeepCopyInto(out *SalesforceSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceSource.
func (in *SalesforceSource) DeepCopy() *SalesforceSource {
	if in == nil {
		return nil
	}
	out := new(SalesforceSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SalesforceSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceSourceList) DeepCopyInto(out *SalesforceSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SalesforceSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceSourceList.
func (in *SalesforceSourceList) DeepCopy() *SalesforceSourceList {
	if in == nil {
		return nil
	}
	out := new(SalesforceSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SalesforceSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceSourceSpec) DeepCopyInto(out *SalesforceSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	out.Auth = in.Auth
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	in.Subscription.DeepCopyInto(&out.Subscription)
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceSourceSpec.
func (in *SalesforceSourceSpec) DeepCopy() *SalesforceSourceSpec {
	if in == nil {
		return nil
	}
	out := new(SalesforceSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceSubscription) DeepCopyInto(out *SalesforceSubscription) {
	*out = *in
	if in.ReplayID != nil {
		in, out := &in.ReplayID, &out.ReplayID
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceSubscription.
func (in *SalesforceSubscription) DeepCopy() *SalesforceSubscription {
	if in == nil {
		return nil
	}
	out := new(SalesforceSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookEventExtensionAttributes) DeepCopyInto(out *WebhookEventExtensionAttributes) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookEventExtensionAttributes.
func (in *WebhookEventExtensionAttributes) DeepCopy() *WebhookEventExtensionAttributes {
	if in == nil {
		return nil
	}
	out := new(WebhookEventExtensionAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSource) DeepCopyInto(out *WebhookSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSource.
func (in *WebhookSource) DeepCopy() *WebhookSource {
	if in == nil {
		return nil
	}
	out := new(WebhookSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSourceList) DeepCopyInto(out *WebhookSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSourceList.
func (in *WebhookSourceList) DeepCopy() *WebhookSourceList {
	if in == nil {
		return nil
	}
	out := new(WebhookSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSourceSpec) DeepCopyInto(out *WebhookSourceSpec) {
	*out = *in
	in.SourceSpec.DeepCopyInto(&out.SourceSpec)
	if in.EventSource != nil {
		in, out := &in.EventSource, &out.EventSource
		*out = new(string)
		**out = **in
	}
	if in.EventExtensionAttributes != nil {
		in, out := &in.EventExtensionAttributes, &out.EventExtensionAttributes
		*out = new(WebhookEventExtensionAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuthUsername != nil {
		in, out := &in.BasicAuthUsername, &out.BasicAuthUsername
		*out = new(string)
		**out = **in
	}
	if in.BasicAuthPassword != nil {
		in, out := &in.BasicAuthPassword, &out.BasicAuthPassword
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.CORSAllowOrigin != nil {
		in, out := &in.CORSAllowOrigin, &out.CORSAllowOrigin
		*out = new(string)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSourceSpec.
func (in *WebhookSourceSpec) DeepCopy() *WebhookSourceSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSourceSpec)
	in.DeepCopyInto(out)
	return out
}
