apiVersion: v1
entries:
  typhoon:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-02-19T12:38:58.09779583Z"
    description: A Helm chart deploying Typhoon on Kubernetes
    digest: bf2b69109dd156fb384d7a2ff8c03406ffa1c26f00a281d1f6b8f2f484ff2d6d
    home: http://github.com/zeiss/typhoon
    name: typhoon
    sources:
    - https://github.com/zeiss/typhoon
    urls:
    - https://github.com/ZEISS/typhoon/releases/download/typhoon-0.2.1/typhoon-0.2.1.tgz
    version: 0.2.1
  typhoon-accounting:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-02-19T12:38:58.235568365Z"
    description: A Helm chart for the Typhoon accounting
    digest: aac23dbdda5aa224e9a16e7c23945ec2d0d81406f307e3e752bd0accda508a5f
    home: http://github.com/zeiss/typhoon
    keywords:
    - messaging
    - jwt
    - auth
    name: typhoon-accounting
    sources:
    - https://github.com/zeiss/typhoon
    urls:
    - https://github.com/ZEISS/typhoon/releases/download/typhoon-accounting-0.2.1/typhoon-accounting-0.2.1.tgz
    version: 0.2.1
  typhoon-web:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-02-19T12:38:58.335849554Z"
    description: A Helm chart for the Typhoon Web application
    digest: 9c238f65ea45256b54820f5ba6ba8be1b9ea3aa90ff66bc8dbeb889379d9d472
    home: http://github.com/zeiss/typhoon
    keywords:
    - messaging
    - jwt
    - auth
    name: typhoon-web
    sources:
    - https://github.com/zeiss/typhoon
    urls:
    - https://github.com/ZEISS/typhoon/releases/download/typhoon-web-0.2.1/typhoon-web-0.2.1.tgz
    version: 0.2.1
generated: "2025-02-19T12:38:58.335860614Z"
