version: 2

project_name: typhoon

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: accounts
    skip: true
    binary: typhoon-accounts
    main: ./cmd/accounts/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
        - -s -w
  - id: web
    skip: true
    binary: typhoon-web
    main: ./cmd/web/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
        - -s -w

archives:
  - id: accounts
    builds:
      - accounts
    name_template: "accounts_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: web
    builds:
      - web
    name_template: "web_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

gomod:
  proxy: true

release:
  header: |
    ## Changelog ({{ .Date }})

    Welcome to this new release! We hope you enjoy the changes we've made.

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: SNAPSHOT-{{.ShortCommit}}
