project_name: typhoon

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: accounts
    binary: typhoon-accounts
    main: ./cmd/accounts/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
        - -s -w

  - id: web
    binary: typhoon-web
    main: ./cmd/web/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
        - -s -w

archives:
  - id: accounts
    builds:
      - accounts
    name_template: "accounts_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: web
    builds:
      - web
    name_template: "web_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates: [
      "ghcr.io/zeiss/{{ .ProjectName }}/accounts:{{ .Version }}-amd64"
    ]
    dockerfile: Dockerfile.accounts
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}-accounts
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/zeiss/{{ .ProjectName }}/typhoon/accounts
      - --label=org.opencontainers.image.source=https://github.com/zeiss/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - image_templates: [
      "ghcr.io/zeiss/{{ .ProjectName }}/accounts:{{ .Version }}-arm64"
    ]
    dockerfile: Dockerfile.accounts
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}-accounts
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/zeiss/{{ .ProjectName }}/typhoon/accounts
      - --label=org.opencontainers.image.source=https://github.com/zeiss/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - image_templates: [
      "ghcr.io/zeiss/{{ .ProjectName }}/web:{{ .Version }}-amd64"
    ]
    dockerfile: Dockerfile.web
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}-web
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/zeiss/{{ .ProjectName }}/typhoon/web
      - --label=org.opencontainers.image.source=https://github.com/zeiss/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - image_templates: [
      "ghcr.io/zeiss/{{ .ProjectName }}/web:{{ .Version }}-arm64"
    ]
    dockerfile: Dockerfile.web
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}-web
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/zeiss/{{ .ProjectName }}/typhoon/web
      - --label=org.opencontainers.image.source=https://github.com/zeiss/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: "ghcr.io/zeiss/{{ .ProjectName }}/web:{{ .Version }}"
    image_templates:
      - 'ghcr.io/zeiss/{{ .ProjectName }}/web:{{ .Version }}-amd64'
      - 'ghcr.io/zeiss/{{ .ProjectName }}/web:{{ .Version }}-arm64'
  - name_template: "ghcr.io/zeiss/{{ .ProjectName }}/accounts:{{ .Version }}"
    image_templates:
      - 'ghcr.io/zeiss/{{ .ProjectName }}/accounts:{{ .Version }}-amd64'
      - 'ghcr.io/zeiss/{{ .ProjectName }}/accounts:{{ .Version }}-arm64'


gomod:
  proxy: true

release:
  draft: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo
