FROM golang:alpine as build

RUN apk --no-cache add ca-certificates

WORKDIR /go/src/app

FROM scratch

WORKDIR /

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY typhoon-web /main

ENTRYPOINT ["/main"]