// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Api_keyScopes    = "api_key.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Account defines model for Account.
type Account struct {
	ContactEmail *string `json:"contactEmail,omitempty"`

	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt   *time.Time          `json:"deletedAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Cluster defines model for Cluster.
type Cluster struct {
	Id  *openapi_types.UUID `json:"id,omitempty"`
	Url *string             `json:"url,omitempty"`
}

// KeyPair defines model for KeyPair.
type KeyPair struct {
	PrivateKey *string `json:"privateKey,omitempty"`
	PublicKey  string  `json:"publicKey"`
}

// NKey An NKey is the private key of a NATS account.
type NKey = string

// Operator defines model for Operator.
type Operator struct {
	ContactEmail *string `json:"contactEmail,omitempty"`

	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Key         *KeyPair   `json:"key,omitempty"`
	Name        string     `json:"name"`
	SigningKeys *[]KeyPair `json:"signingKeys,omitempty"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PaginatedResult defines model for PaginatedResult.
type PaginatedResult struct {
	Limit   *float32       `json:"limit,omitempty"`
	Offset  *float32       `json:"offset,omitempty"`
	Results *[]interface{} `json:"results,omitempty"`
	Total   *float32       `json:"total,omitempty"`
}

// SigningKeyGroup defines model for SigningKeyGroup.
type SigningKeyGroup struct {
	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt   *time.Time            `json:"deletedAt,omitempty"`
	Description *string               `json:"description,omitempty"`
	Disabled    *bool                 `json:"disabled,omitempty"`
	Id          *openapi_types.UUID   `json:"id,omitempty"`
	IsScoped    *bool                 `json:"is_scoped,omitempty"`
	Name        string                `json:"name"`
	Scope       *SigningKeyGroupScope `json:"scope,omitempty"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// SigningKeyGroupScope defines model for SigningKeyGroupScope.
type SigningKeyGroupScope struct {
	Data          *int                           `json:"data,omitempty"`
	Payload       *int                           `json:"payload,omitempty"`
	Publish       *SigningKeyGroupScopePublish   `json:"publish,omitempty"`
	Subscribe     *SigningKeyGroupScopeSubscribe `json:"subscribe,omitempty"`
	Subscriptions *int                           `json:"subscriptions,omitempty"`
}

// SigningKeyGroupScopePublish defines model for SigningKeyGroupScopePublish.
type SigningKeyGroupScopePublish struct {
	Allow *[]string `json:"allow,omitempty"`
	Deny  *[]string `json:"deny,omitempty"`
}

// SigningKeyGroupScopeSubscribe defines model for SigningKeyGroupScopeSubscribe.
type SigningKeyGroupScopeSubscribe struct {
	Allow *[]string `json:"allow,omitempty"`
	Deny  *[]string `json:"deny,omitempty"`
}

// System defines model for System.
type System struct {
	Cluster Cluster `json:"cluster"`

	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt *time.Time `json:"deletedAt,omitempty"`

	// Description A description of the system.
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Name Name of the system
	Name     string    `json:"name"`
	Operator *Operator `json:"operator,omitempty"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Systems defines model for Systems.
type Systems = []System

// Team defines model for Team.
type Team struct {
	ContactEmail *string `json:"contactEmail,omitempty"`

	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt   *time.Time          `json:"deletedAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Creation date and time
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Creation date and time
	DeletedAt *time.Time          `json:"deletedAt,omitempty"`
	Email     *string             `json:"email,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Jwt       *string             `json:"jwt,omitempty"`
	Key       *string             `json:"key,omitempty"`
	Name      string              `json:"name"`

	// UpdatedAt Creation date and time
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Version defines model for Version.
type Version struct {
	Date    string `json:"date"`
	Version string `json:"version"`
}

// AccountId defines model for accountId.
type AccountId = openapi_types.UUID

// GroupId defines model for groupId.
type GroupId = openapi_types.UUID

// LimitParam defines model for limitParam.
type LimitParam = int

// OffsetParam defines model for offsetParam.
type OffsetParam = int

// TeamId defines model for teamId.
type TeamId = openapi_types.UUID

// CreateOperator defines model for CreateOperator.
type CreateOperator struct {
	ContactEmail *string `json:"contactEmail,omitempty"`
	Description  *string `json:"description,omitempty"`
	Name         string  `json:"name"`
}

// CreateTeam defines model for CreateTeam.
type CreateTeam = Team

// ListOperatorParams defines parameters for ListOperator.
type ListOperatorParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOperatorJSONBody defines parameters for CreateOperator.
type CreateOperatorJSONBody struct {
	ContactEmail *string `json:"contactEmail,omitempty"`
	Description  *string `json:"description,omitempty"`
	Name         string  `json:"name"`
}

// ListTeamsParams defines parameters for ListTeams.
type ListTeamsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOperatorJSONRequestBody defines body for CreateOperator for application/json ContentType.
type CreateOperatorJSONRequestBody CreateOperatorJSONBody

// CreateSystemJSONRequestBody defines body for CreateSystem for application/json ContentType.
type CreateSystemJSONRequestBody = System

// UpdateSystemJSONRequestBody defines body for UpdateSystem for application/json ContentType.
type UpdateSystemJSONRequestBody = System

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = Team

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = SigningKeyGroup

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = SigningKeyGroup

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = User

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = User

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW2/bOBb+KwQ7j4qlpLtA4bdM2w0yHbRBnc4CmxoDWjq22UqkhqSSMQz/9wVvuliS",
	"b4ndy+RRInl47vp4eOwljnmWcwZMSTxc4pwIkoECYZ5IHPOCqetEPyQgY0FzRTnDQ3w7B0QTxKdIzQG5",
	"iUhxJEAJCvcwwAGmemZO1BwHmJEM8LBGMsAC/iqogAQPlSggwDKeQ0b0XlMuMqLwEBcF1TPVIteLpRKU",
	"zfBqFeCZ4EW+nTEzbQe2PLnHMZXSjKobrcJuvliRTUBIzRxVkEnHWCFYydZfBYhFxZehiOtcJDAlRarw",
	"8CIKcEb+plmR4eG/9QNl9uG85I0yBTMQhjk+nUrYzl2DOfmV5mgCUy4ASUWEomym38c8TSFWRsUCZJEq",
	"JEH1CWF37paiznfUybcCkm03tJ61g50dsceYeWUXg1S/8oSCCZTXAoiCDzkIorjQb2LOFDBloijPUxoT",
	"zXb4RWrel7XtcsFzEMoR0stIrN5mhKb6eW3zoKmDjnEr57LDOSuJ7+yscSkbn3yBWGnZVoGT5Rasm+ws",
	"xy8CpniIX4RVQgntqAwNsZUl797pJZc2FxyghdjwmFyqtlsY9ilnKCEKEGEJUjQDHGD4m2R5qulcRBfn",
	"Z9H52cvoNno1fBkNo+h/OKgMr1eeuVUdBkjhm2292fY06fJfAST5wNKF9/RdXSbARZ58Gy3v5q0Bfp0W",
	"UoFoO9CBmihEenDsBPgdLG4IFU1l4SG+RG4EUYkIyotJSuMwF/Re6+4rLFBOqBh8ZjhYE8PNeQeLhjgT",
	"IuHlRZeHWNq7zl8TrFrcJd17R7XpB5cM6QEtmc7CdaH4FBH0/vJ25NGBlXAHKep59DkxPH1iKDW/NSC+",
	"Wptvyu3e6zclEklnjLLZO1jY6NTwYg+6jh4Rgix+iLx0Q2aUaRY/GmzU9mML6ypVWeiFS5TWOWSBlqyN",
	"lRpRXJG0Y9Gqg7lRaYwrDXo7guw5hrqAF5VkkkLSQK9Tksoqbiacp0DYIz7FVP4pY57vukt/wGki2yJs",
	"zRFGZs2PEF6djLfcOCGqddRYP14EOCeLlJNkh4n66yjnhyj1xi3VhikmWp+Tg4wzKhdXlIxl5Db2Vztq",
	"8aYSsqlMkqb8oZG7Wz63npMSYIt9VuzK46iuwu+Dy4VUkHUk0gqebjK1R7HP8MWm3jWEiWrP/rQvjcYH",
	"XcQeeQhqbv6eZNDcsyE1FGcPINXZeRcjvIZiN5m/RLvfW+oNSgce9zr97njOBcnKFK2u7YrzKGpHpK88",
	"PCP/55LA/tjgk+yqB/wznQN6g+VAt/jyoDrJuWPiT+RGf4CQLqZaqLJbpPtqxeY9/cTA0uqowgZYQlwI",
	"qhYjnTwdtsnpn07Ppq49B5KAqF2suPEqoeb0HZiMOgEiQFwWygA7+/Qfr6zf/nvrK/PmdGFGKypzpXKT",
	"Xjn/SsHTMBzYVxUHv43ejkbXH95fv2kzsTIkmCyMNHftWvJYR8qUMlri2VqhOC5L0h9B5pxJ6Cv57VEP",
	"b9W+A0zZlLc98gW6ZkrwpIj1i8/sM7td5HPOmannMQT3wBSaCJrMAE25QDXhpPFgCeKexiBtBSylMTgR",
	"nOYucxLPAV0MIuyKkEbvchiGDw8PA2KGB1zMQrdWhr9fv377fvT27GIQDeYqSw1SpcrEh2fv8uYa1xwT",
	"nw+iQeSgCSM5xUP8cnBuNs2Jmhs1hh62mKeZLUXYd5Sz6wQP8e9UqhK0BI0rw7tuDFBNCeu3UKtg6/Ta",
	"jdpqbMqjSRH3u5Bw7mGYv4iivW4wSJp+mPbK4HHMem1HC9H0xFqdZidkVAeA2w4bY+OnTf8cFXEMUk6L",
	"NEVeAY0sYmSqJ4E7k+qHlanHWrmyyDIiFs7CiKQpqmYEWJGZ0XvJ7lifirlUtqDFvhpBr6D0jV8X9tqu",
	"6T0z6HOeZQmZzcRfvCyDCU8WL0Ka2CBtklu7edvFRfzdXW9ps3G9F67tsGp52fmT3ZNVm7StbNlIrGFL",
	"S9m3EhHE4KE0V7e1VgEOZYXaXWw3d/lobqM1vVT7AJ+ijDAyg8Qdf6Q+c7XTgT8M/KARWJ1Nnjb+2gHV",
	"oU1vKcdEX1TZ4d6YGvnTaTOi7D57x1NFbb9oepIo8NZwV+1HirVql0MirSwGtKxXi7Jw6dW/spFmTgJt",
	"89mBTgvebe56sPSR4sjS6G56KJ1gU9vDOkBqf03/1U4XleuvaeuNYUdry7E4WaDrNzrCnirtXPX4/M4a",
	"850iR9VZ1FXQyn0CK9OFuSxNUy/twdlD2vRRdKC2T+bI9TiV2WPbUyvstBkkOkEG6Q0La4R2WOikoYBk",
	"m0H3rZnxjLgf/b23/UgnRtvWvn1IWznb+ng2LPZhAT3YiwTMynUc4Jvo9kIBntJxELU3wtG+8L7r7JDv",
	"u7Kir1mjDNNwaRW66o3Xq05DbI9WZ6jV+IiJq08xvWnrCpRWjOmxXM9YpSpC1+azOYdd+kmHKiZ4Tnj7",
	"JzzfaXnqnFe6RF/a8xNs3WznsCt9LVyWDeUbY9EroOV1x+kRDpbH630/ZmYo/WTv5MDK3wBsTxB1o4Wm",
	"835zzriyU46XMSrDPKeXg+onay1lp04zzof6koxrPzRdqXaqTTelz+6Ku4x0vcDLyh70/4amBb7qCaH8",
	"QUsXRAv6AZz38j4Q18XVkWJn/I3qReved+TCUXu7gypI60558HfPpdBw6Vxol2LTCb1i+2Tv+k9Xc1rX",
	"bav81AIIP4pColP68bYDwQY9b6hBfceq/kbJ6fswaq041WfXXTNSIWHLBfInM+MZ0n2vkM70UZ0ax1m3",
	"6YNxZvRA5KbF6QVuRtZDcds2YBZgzffetbcOnn4u1GYd7LhQze9xCD4rrAEOhGTGV8OlNf0ugOx09u6u",
	"TTgnfdrCxGHoTbOyHbD9lAqLju762yBdU/kbUNzPov9TZrZvaN4K3NUtrNNZrXG1M9b+KPtVjyaN38L/",
	"RUDJte8LUHNAcSEEMIUcv/52+vLmunEPDuIeTLfTavt3Tfr22jvb5zpegyj1pte7sXbEBmgxb8q+3DuL",
	"W8z+XZfqb+AeUp5nWgY7q9HsOQzDlMcknXOphq+iV1FIchren5sPtJOu455eAiIC6vf0vklgskCuEXRQ",
	"RU3Z6bSZlPnEITUnyrwqpD4NtKm5K7wttASdzTRyq5GDxPy7CLDEds+aPxvpoO+Wapj5/wAAAP//1Bhv",
	"I6pGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
