# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0

info:
  version: 1.0.0
  title: Thyphoon Account Server API
  summary: |-
    The account server provides the JWT tokens for the accounts in NATS 2.0.
  contact:
    name: Sebastian Doell
    email: sebastian@katallaxie.dev
  description: |
    # Introduction

    The account server provides the JWT tokens for the accounts in NATS 2.0.
  license:
    name: Apache 2.0
    identifier: Apache-2.0

servers:
  - url: http://localhost:8080/jwt/v1
    description: Development server
  - url: /jwt/v1
    description: Production server

tags:
  - name: Help
    description: |-
      These are the help endpoints.
  - name: Account
    description: |-
      These are the account endpoints.

paths:
  /accounts/:
    get:
      tags:
        - Help
      operationId: getHelp
      summary: This is a test endpoint
      description: |-
        This endpoint is used to test the endpoint
      responses:
        '200':
          description: Sucessful test
        default:
          description: Unexpected error

  /accounts/{pubKey}:
    get:
      tags:
        - Account
      operationId: getAccountToken
      summary: Get account information
      description: |-
        Get the account information for the given public key.
      parameters:
        - $ref: '#/components/parameters/pubKey'
        - $ref: '#/components/parameters/ifNoneMatch'
      responses:
        '200':
          description: Account information
          headers:
            Cache-Control:
              description: The cache control header.
              example: "max-age: 86400, must-revalidate, private"
              schema:
                type: string
            ETag:
              description: The current ETag of the token.
              example: "SN6ZQ37REZOIUOCSHNDP3X7E7B6ZMZ6XULX24KV23LMRSZLXD36A"
              schema:
                type: string
          content:
            application/jwt:
              schema:
                $ref: "#/components/schemas/JWT"
        '404':
          description: The token was not found.
        '304':
          description: The token was not modified.
        default:
          description: Unexpected error

components:
  schemas:
    JWT:
      type: string
      format: jwt
      description: The JWT token.

  parameters:
    pubKey:
      name: pubKey
      in: path
      required: true
      description: The public key of the account.
      schema:
        type: string
    ifNoneMatch:
      name: If-None-Match
      in: header
      required: false
      description: The ETag of the token.
      example: SN6ZQ37REZOIUOCSHNDP3X7E7B6ZMZ6XULX24KV23LMRSZLXD36A
      schema:
        type: string
        
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - bearerAuth: []
  - apiKey: []
