apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-webhook
  labels:
    app.kubernetes.io/part-of: typhoon
    typhoon.zeiss.com/release: devel

rules:
# Routing admin
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  - splitters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Routing statuses update
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - splitters/status
  - filters/status
  verbs:
  - update


- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - xslttransformations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - xslttransformations/status
  verbs:
  - update

# Events admin
- apiGroups:
  - ''
  resources:
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# For manipulating certs into secrets.
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch

# Validation webhook gets system namespace to use it as an owner.
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get

# For actually registering our webhook.
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
