apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-controller
  labels:
    app.kubernetes.io/part-of: typhoon

rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Manage receive-adapters
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch

# Read reconciled typhoon resources and update their statuses
# +rbac-check
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - cloudeventssources
  - httppollersources
  - kafkasources
  - mongodbsources
  - webhooksources
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - cloudeventssources/status
  - httppollersources/status
  - kafkasources/status
  - webhooksources/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - cloudeventstargets
  - httptargets
  - logzmetricstargets
  - splunktargets
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - cloudeventstargets/status
  - httptargets/status
  - logzmetricstargets/status
  - logztargets/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations
  - synchronizers
  - transformations
  - xmltojsontransformations
  - xslttransformations
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations/status
  - synchronizers/status
  - transformations/status
  - xmltojsontransformations/status
  - xslttransformations/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  - splitters
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters/status
  - splitters/status
  verbs:
  - update

# Ensure compatibility with the OwnerReferencesPermissionEnforcement Admission Controller
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
# +rbac-check:subresource=finalizers
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - cloudeventssources/finalizers
  - httppollersources/finalizers
  - kafkasources/finalizers
  - webhooksources/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - cloudeventstargets/finalizers
  - httptargets/finalizers
  - logzmetricstargets/finalizers
  - logztargets/finalizers
  - splunktargets/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations/finalizers
  - synchronizers/finalizers
  - transformations/finalizers
  - xmltojsontransformations/finalizers
  - xslttransformations/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters/finalizers
  - splitters/finalizers
  verbs:
  - update

# Manage resource-specific ServiceAccounts and RoleBindings
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - serviceaccounts/finalizers
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  # Only multi-tenant components receive permissions via RoleBindings to
  # interact with the Kubernetes API.
  resourceNames:
  - splitter-adapter
  verbs:
  - update

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Required by Function controller to store, and mount user's code
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

# Read controller configurations
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

# Observe status of Pods and their ancestors
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - watch

---

# This role is used to grant receive adapters read-only access to per-component
# configurations such as logging, observability and tracing.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-config-watcher
  labels:
    app.kubernetes.io/part-of: typhoon
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssnssource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Read Source resources and update their statuses
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awssnssources
  verbs:
  - list
  - watch
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awssnssources/status
  verbs:
  - patch

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zendesksource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Read Source resources
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - zendesksources
  verbs:
  - list
  - watch

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splitter-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - splitters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

# This role provides readonly access to "Source" duck types.
# All the rules it contains get aggregated into the "source-observer" ClusterRole provided by Knative Eventing.
# see https://github.com/knative/eventing/blob/release-0.26/docs/spec/sources.md#source-rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-source-observer
  labels:
    app.kubernetes.io/part-of: typhoon
    duck.knative.dev/source: 'true'
rules:
# +rbac-check
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - cloudeventssources
  - httppollersources
  - kafkasources
  - webhooksources
  verbs:
  - get
  - list
  - watch

---

# This aggregated role grants read-only access to Addressables.
# It is intended mainly to allow sink resolvers to resolve URLs from object references.
#
# NOTE: This same role can also be found in Knative Eventing. It is duplicated here to allow running typhoon in a
# cluster which doesn't have Knative Eventing deployed.
# Source:
#   https://github.com/knative/eventing/blob/knative-v1.1.0/config/core/roles/addressable-resolvers-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addressable-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: 'true'
rules: []  # Rules are automatically filled in by the Kubernetes controller manager.

---

# This role provides readonly access to "Addressable" duck types.
# All the rules it contains get aggregated into the "addressable-resolver" ClusterRole.
# https://github.com/knative/eventing/blob/release-0.26/config/core/roles/addressable-resolvers-clusterrole.yaml#L15-L28
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-addressable-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
    duck.knative.dev/addressable: 'true'
rules:
# +rbac-check
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - awscomprehendtargets
  - awsdynamodbtargets
  - awseventbridgetargets
  - awskinesistargets
  - awslambdatargets
  - awss3targets
  - awssnstargets
  - awssqstargets
  - azureeventhubstargets
  - azuresentineltargets
  - azureservicebustargets
  - cloudeventstargets
  - datadogtargets
  - elasticsearchtargets
  - googlecloudfirestoretargets
  - googlecloudpubsubtargets
  - googlecloudstoragetargets
  - googlecloudworkflowstargets
  - googlesheettargets
  - httptargets
  - ibmmqtargets
  - jiratargets
  - logzmetricstargets
  - logztargets
  - mongodbtargets
  - oracletargets
  - salesforcetargets
  - sendgridtargets
  - slacktargets
  - solacetargets
  - splunktargets
  - twiliotargets
  - zendesktargets
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations
  - synchronizers
  - transformations
  - xmltojsontransformations
  - xslttransformations
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  - splitters
  verbs:
  - get
  - list
  - watch
# Allow resolving URLs of a few additional common types which are not supplied by typhoon.
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - routes
  - services
  verbs:
  - get
  - list
  - watch
