apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-core-addressable-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
    duck.knative.dev/addressable: 'true'
rules:
# +rbac-check
- apiGroups:
  - eventing.typhoon.zeiss.com
  resources:
  - memorybrokers
  - redisbrokers
  verbs:
  - get
  - list
  - watch