apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-controller
  labels:
    app.kubernetes.io/part-of: typhoon

rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Manage receive-adapters
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch

# Read reconciled typhoon resources and update their statuses
# +rbac-check
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awscloudwatchlogssources
  - awscloudwatchsources
  - awscodecommitsources
  - awscognitoidentitysources
  - awscognitouserpoolsources
  - awsdynamodbsources
  - awseventbridgesources
  - awskinesissources
  - awsperformanceinsightssources
  - awss3sources
  - awssnssources
  - awssqssources
  - azureactivitylogssources
  - azureblobstoragesources
  - azureeventgridsources
  - azureeventhubssources
  - azureiothubsources
  - azurequeuestoragesources
  - azureservicebusqueuesources
  - azureservicebussources
  - azureservicebustopicsources
  - cloudeventssources
  - googlecloudauditlogssources
  - googlecloudbillingsources
  - googlecloudpubsubsources
  - googlecloudsourcerepositoriessources
  - googlecloudstoragesources
  - httppollersources
  - ibmmqsources
  - kafkasources
  - mongodbsources
  - ocimetricssources
  - salesforcesources
  - slacksources
  - solacesources
  - twiliosources
  - webhooksources
  - zendesksources
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awscloudwatchlogssources/status
  - awscloudwatchsources/status
  - awscodecommitsources/status
  - awscognitoidentitysources/status
  - awscognitouserpoolsources/status
  - awsdynamodbsources/status
  - awseventbridgesources/status
  - awskinesissources/status
  - awsperformanceinsightssources/status
  - awss3sources/status
  - awssnssources/status
  - awssqssources/status
  - azureactivitylogssources/status
  - azureblobstoragesources/status
  - azureeventgridsources/status
  - azureeventhubssources/status
  - azureiothubsources/status
  - azurequeuestoragesources/status
  - azureservicebusqueuesources/status
  - azureservicebussources/status
  - azureservicebustopicsources/status
  - cloudeventssources/status
  - googlecloudauditlogssources/status
  - googlecloudbillingsources/status
  - googlecloudpubsubsources/status
  - googlecloudsourcerepositoriessources/status
  - googlecloudstoragesources/status
  - httppollersources/status
  - ibmmqsources/status
  - kafkasources/status
  - mongodbsources/status
  - ocimetricssources/status
  - salesforcesources/status
  - slacksources/status
  - solacesources/status
  - twiliosources/status
  - webhooksources/status
  - zendesksources/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - awscomprehendtargets
  - awsdynamodbtargets
  - awseventbridgetargets
  - awskinesistargets
  - awslambdatargets
  - awss3targets
  - awssnstargets
  - awssqstargets
  - azureeventhubstargets
  - azuresentineltargets
  - azureservicebustargets
  - cloudeventstargets
  - datadogtargets
  - elasticsearchtargets
  - googlecloudfirestoretargets
  - googlecloudpubsubtargets
  - googlecloudstoragetargets
  - googlecloudworkflowstargets
  - googlesheettargets
  - httptargets
  - ibmmqtargets
  - jiratargets
  - kafkatargets
  - logzmetricstargets
  - logztargets
  - mongodbtargets
  - oracletargets
  - salesforcetargets
  - sendgridtargets
  - slacktargets
  - solacetargets
  - splunktargets
  - twiliotargets
  - zendesktargets
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - awscomprehendtargets/status
  - awsdynamodbtargets/status
  - awseventbridgetargets/status
  - awskinesistargets/status
  - awslambdatargets/status
  - awss3targets/status
  - awssnstargets/status
  - awssqstargets/status
  - azureeventhubstargets/status
  - azuresentineltargets/status
  - azureservicebustargets/status
  - cloudeventstargets/status
  - datadogtargets/status
  - elasticsearchtargets/status
  - googlecloudfirestoretargets/status
  - googlecloudpubsubtargets/status
  - googlecloudstoragetargets/status
  - googlecloudworkflowstargets/status
  - googlesheettargets/status
  - httptargets/status
  - ibmmqtargets/status
  - jiratargets/status
  - kafkatargets/status
  - logzmetricstargets/status
  - logztargets/status
  - mongodbtargets/status
  - oracletargets/status
  - salesforcetargets/status
  - sendgridtargets/status
  - slacktargets/status
  - solacetargets/status
  - splunktargets/status
  - twiliotargets/status
  - zendesktargets/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations
  - synchronizers
  - transformations
  - xmltojsontransformations
  - xslttransformations
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations/status
  - synchronizers/status
  - transformations/status
  - xmltojsontransformations/status
  - xslttransformations/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions/status
  verbs:
  - update
# +rbac-check
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  - splitters
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters/status
  - splitters/status
  verbs:
  - update

# Ensure compatibility with the OwnerReferencesPermissionEnforcement Admission Controller
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
# +rbac-check:subresource=finalizers
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awscloudwatchlogssources/finalizers
  - awscloudwatchsources/finalizers
  - awscodecommitsources/finalizers
  - awscognitoidentitysources/finalizers
  - awscognitouserpoolsources/finalizers
  - awsdynamodbsources/finalizers
  - awseventbridgesources/finalizers
  - awskinesissources/finalizers
  - awsperformanceinsightssources/finalizers
  - awss3sources/finalizers
  - awssnssources/finalizers
  - awssqssources/finalizers
  - azureactivitylogssources/finalizers
  - azureblobstoragesources/finalizers
  - azureeventgridsources/finalizers
  - azureeventhubssources/finalizers
  - azureiothubsources/finalizers
  - azurequeuestoragesources/finalizers
  - azureservicebusqueuesources/finalizers
  - azureservicebussources/finalizers
  - azureservicebustopicsources/finalizers
  - cloudeventssources/finalizers
  - googlecloudauditlogssources/finalizers
  - googlecloudbillingsources/finalizers
  - googlecloudpubsubsources/finalizers
  - googlecloudsourcerepositoriessources/finalizers
  - googlecloudstoragesources/finalizers
  - httppollersources/finalizers
  - ibmmqsources/finalizers
  - kafkasources/finalizers
  - mongodbsources/finalizers
  - ocimetricssources/finalizers
  - salesforcesources/finalizers
  - slacksources/finalizers
  - solacesources/finalizers
  - twiliosources/finalizers
  - webhooksources/finalizers
  - zendesksources/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - awscomprehendtargets/finalizers
  - awsdynamodbtargets/finalizers
  - awseventbridgetargets/finalizers
  - awskinesistargets/finalizers
  - awslambdatargets/finalizers
  - awss3targets/finalizers
  - awssnstargets/finalizers
  - awssqstargets/finalizers
  - azureeventhubstargets/finalizers
  - azuresentineltargets/finalizers
  - azureservicebustargets/finalizers
  - cloudeventstargets/finalizers
  - datadogtargets/finalizers
  - elasticsearchtargets/finalizers
  - googlecloudfirestoretargets/finalizers
  - googlecloudpubsubtargets/finalizers
  - googlecloudstoragetargets/finalizers
  - googlecloudworkflowstargets/finalizers
  - googlesheettargets/finalizers
  - httptargets/finalizers
  - ibmmqtargets/finalizers
  - jiratargets/finalizers
  - kafkatargets/finalizers
  - logzmetricstargets/finalizers
  - logztargets/finalizers
  - mongodbtargets/finalizers
  - oracletargets/finalizers
  - salesforcetargets/finalizers
  - sendgridtargets/finalizers
  - slacktargets/finalizers
  - solacetargets/finalizers
  - splunktargets/finalizers
  - twiliotargets/finalizers
  - zendesktargets/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations/finalizers
  - synchronizers/finalizers
  - transformations/finalizers
  - xmltojsontransformations/finalizers
  - xslttransformations/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions/finalizers
  verbs:
  - update
# +rbac-check:subresource=finalizers
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters/finalizers
  - splitters/finalizers
  verbs:
  - update

# Set finalizers
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awseventbridgesources
  - awss3sources
  - awssnssources
  - azureactivitylogssources
  - azureblobstoragesources
  - azureeventgridsources
  - azureservicebusqueuesources
  - azureservicebussources
  - azureservicebustopicsources
  - googlecloudauditlogssources
  - googlecloudbillingsources
  - googlecloudpubsubsources
  - googlecloudsourcerepositoriessources
  - googlecloudstoragesources
  - zendesksources
  verbs:
  - patch

# Manage resource-specific ServiceAccounts and RoleBindings
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - serviceaccounts/finalizers
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  # Only multi-tenant components receive permissions via RoleBindings to
  # interact with the Kubernetes API.
  resourceNames:
  - awssnssource-adapter
  - zendesksource-adapter
  - filter-adapter
  - splitter-adapter
  verbs:
  - update

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Required by Function controller to store, and mount user's code
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

# Read controller configurations
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

# Observe status of Pods and their ancestors
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - watch

---

# This role is used to grant receive adapters read-only access to per-component
# configurations such as logging, observability and tracing.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-config-watcher
  labels:
    app.kubernetes.io/part-of: typhoon
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awssnssource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Read Source resources and update their statuses
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awssnssources
  verbs:
  - list
  - watch
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awssnssources/status
  verbs:
  - patch

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zendesksource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Read Source resources
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - zendesksources
  verbs:
  - list
  - watch

# Read credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filter-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splitter-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - splitters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

# This role provides readonly access to "Source" duck types.
# All the rules it contains get aggregated into the "source-observer" ClusterRole provided by Knative Eventing.
# see https://github.com/knative/eventing/blob/release-0.26/docs/spec/sources.md#source-rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-source-observer
  labels:
    app.kubernetes.io/part-of: typhoon
    duck.knative.dev/source: 'true'
rules:
# +rbac-check
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awscloudwatchlogssources
  - awscloudwatchsources
  - awscodecommitsources
  - awscognitoidentitysources
  - awscognitouserpoolsources
  - awsdynamodbsources
  - awseventbridgesources
  - awskinesissources
  - awsperformanceinsightssources
  - awss3sources
  - awssnssources
  - awssqssources
  - azureactivitylogssources
  - azureblobstoragesources
  - azureeventgridsources
  - azureeventhubssources
  - azureiothubsources
  - azurequeuestoragesources
  - azureservicebusqueuesources
  - azureservicebussources
  - azureservicebustopicsources
  - cloudeventssources
  - googlecloudauditlogssources
  - googlecloudbillingsources
  - googlecloudpubsubsources
  - googlecloudsourcerepositoriessources
  - googlecloudstoragesources
  - httppollersources
  - ibmmqsources
  - kafkasources
  - mongodbsources
  - ocimetricssources
  - salesforcesources
  - slacksources
  - solacesources
  - twiliosources
  - webhooksources
  - zendesksources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sources.typhoon.zeiss.com
  resources:
  - awscloudwatchlogssources/finalizers
  - awscloudwatchsources/finalizers
  - awscodecommitsources/finalizers
  - awscognitoidentitysources/finalizers
  - awscognitouserpoolsources/finalizers
  - awsdynamodbsources/finalizers
  - awskinesissources/finalizers
  - awsperformanceinsightssources/finalizers
  - awss3sources/finalizers
  - awssnssources/finalizers
  - awssqssources/finalizers
  - azureactivitylogssources/finalizers
  - azureblobstoragesources/finalizers
  - azureeventgridsources/finalizers
  - azureeventhubssources/finalizers
  - azureiothubsources/finalizers
  - azurequeuestoragesources/finalizers
  - azureservicebusqueuesources/finalizers
  - azureservicebussources/finalizers
  - azureservicebustopicsources/finalizers
  - googlecloudauditlogssources/finalizers
  - googlecloudbillingsources/finalizers
  - googlecloudpubsubsources/finalizers
  - googlecloudsourcerepositoriessources/finalizers
  - googlecloudstoragesources/finalizers
  verbs:
  - update

---

# This aggregated role grants read-only access to Addressables.
# It is intended mainly to allow sink resolvers to resolve URLs from object references.
#
# NOTE: This same role can also be found in Knative Eventing. It is duplicated here to allow running typhoon in a
# cluster which doesn't have Knative Eventing deployed.
# Source:
#   https://github.com/knative/eventing/blob/knative-v1.1.0/config/core/roles/addressable-resolvers-clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addressable-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: 'true'
rules: []  # Rules are automatically filled in by the Kubernetes controller manager.

---

# This role provides readonly access to "Addressable" duck types.
# All the rules it contains get aggregated into the "addressable-resolver" ClusterRole.
# https://github.com/knative/eventing/blob/release-0.26/config/core/roles/addressable-resolvers-clusterrole.yaml#L15-L28
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typhoon-addressable-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
    duck.knative.dev/addressable: 'true'
rules:
# +rbac-check
- apiGroups:
  - targets.typhoon.zeiss.com
  resources:
  - awscomprehendtargets
  - awsdynamodbtargets
  - awseventbridgetargets
  - awskinesistargets
  - awslambdatargets
  - awss3targets
  - awssnstargets
  - awssqstargets
  - azureeventhubstargets
  - azuresentineltargets
  - azureservicebustargets
  - cloudeventstargets
  - datadogtargets
  - elasticsearchtargets
  - googlecloudfirestoretargets
  - googlecloudpubsubtargets
  - googlecloudstoragetargets
  - googlecloudworkflowstargets
  - googlesheettargets
  - httptargets
  - ibmmqtargets
  - jiratargets
  - kafkatargets
  - logzmetricstargets
  - logztargets
  - mongodbtargets
  - oracletargets
  - salesforcetargets
  - sendgridtargets
  - slacktargets
  - solacetargets
  - splunktargets
  - twiliotargets
  - zendesktargets
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - flow.typhoon.zeiss.com
  resources:
  - jqtransformations
  - synchronizers
  - transformations
  - xmltojsontransformations
  - xslttransformations
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - extensions.typhoon.zeiss.com
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
# +rbac-check
- apiGroups:
  - routing.typhoon.zeiss.com
  resources:
  - filters
  - splitters
  verbs:
  - get
  - list
  - watch
# Allow resolving URLs of a few additional common types which are not supplied by typhoon.
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - routes
  - services
  verbs:
  - get
  - list
  - watch
