apiVersion: v1
kind: ServiceAccount
metadata:
  name: typhoon-controller
  namespace: typhoon
  labels:
    app.kubernetes.io/part-of: typhoon
    typhoon.zeiss.com/release: devel

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: typhoon-webhook
  namespace: typhoon
  labels:
    app.kubernetes.io/part-of: typhoon
    typhoon.zeiss.com/release: devel
