apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-core-controller
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-core-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typhoon-core-controller

---

# Controller must be granted the same permissions it assigns
# to the broker deployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-core-controller-for-brokers
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-core-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typhoon-broker

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-core-controller-resolver
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-core-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver-typhoon

---

# If Knative Eventing is installed, use also the addressable-resolver.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-core-controller-resolver-knative
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-core-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-controller
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typhoon-controller

---

# Permissions not required by controllers directly, but granted to
# receive-adapters via RoleBindings.
#
# Without them, the following error is thrown:
#   "attempting to grant RBAC permissions not currently held"
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awssnssource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awssnssource-adapter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zendesksource-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zendesksource-adapter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filter-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filter-adapter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: splitter-adapter
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splitter-adapter

---

# Resolve sink URIs when Knative is installed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-controller-addressable-resolver-from-knative
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver

---

# Resolve sink URIs when typhoon Core is installed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoon-controller-addressable-resolver-from-typhoon
  labels:
    app.kubernetes.io/part-of: typhoon
subjects:
- kind: ServiceAccount
  name: typhoon-controller
  namespace: typhoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver-typhoon
