apiVersion: apps/v1
kind: Deployment
metadata:
  name: typhoon-controller
  namespace: typhoon
  labels:
    app.kubernetes.io/part-of: typhoon

spec:
  replicas: 1
  selector:
    matchLabels:
      app: typhoon-controller

  template:
    metadata:
      labels:
        app: typhoon-controller

    spec:
      serviceAccountName: typhoon-controller

      containers:
      - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://github.com/zeiss/typhoon/cmd/controller

        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 500Mi

        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Logging/observability configuration
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: typhoon.zeiss.com
        - name: HTTPPOLLERSOURCE_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/httppollersource-adapter
        - name: KAFKASOURCE_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/kafkasource-adapter
        - name: WEBHOOKSOURCE_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/webhooksource-adapter
        - name: CLOUDEVENTSTARGET_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/cloudeventstarget-adapter
        - name: HTTPTARGET_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/httptarget-adapter
        - name: KAFKATARGET_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/kafkatarget-adapter
        - name: LOGZTARGET_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/logztarget-adapter
        - name: OPENTELEMETRYTARGET_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/opentelemetrytarget-adapter
        # Flow adapters
        - name: JQTRANSFORMATION_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/jqtransformation-adapter
        - name: SYNCHRONIZER_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/synchronizer-adapter
        - name: TRANSFORMATION_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/transformation-adapter
        - name: XMLTOJSONTRANSFORMATION_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/xmltojsontransformation-adapter
        # Routing adapters
        - name: FILTER_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/filter-adapter
        - name: SPLITTER_IMAGE
          value: ko://github.com/zeiss/typhoon/cmd/splitter-adapter
        # Function Runtimes
        - name: RUNTIME_KLR_PYTHON
          value: gcr.io/typhoon/knative-lambda-python310:v1.26.0
        - name: RUNTIME_KLR_NODE
          value: gcr.io/typhoon/knative-lambda-node18:v1.26.0
        - name: RUNTIME_KLR_RUBY
          value: gcr.io/typhoon/knative-lambda-ruby32:v1.26.0
        # Custom build adapters
        - name: IBMMQSOURCE_IMAGE
          value: gcr.io/typhoon/ibmmqsource-adapter:latest
        - name: IBMMQTARGET_IMAGE
          value: gcr.io/typhoon/ibmmqtarget-adapter:latest
        - name: XSLTTRANSFORMATION_IMAGE
          value: gcr.io/typhoon/xslttransformation-adapter:latest

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [all]

        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
