apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nats
  namespace: knative-eventing
data:
  eventing-nats: |
    url: nats://sample-nats.default.svc.cluster.local:4222
    auth:
      credentialFile:
        secret:
          key: user.creds
          name: typhoon-credentials 
    connOpts:
      retryOnFailedConnect: true
      maxReconnects: 5
      reconnectWaitMilliseconds: 2000
      reconnectJitterMilliseconds: 100
      reconnectJitterTLSMilliseconds: 1000