apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-account-private-key
  namespace: knative-eventing
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-account-signing-key
  namespace: knative-eventing
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsAccount
metadata:
  name: typhoon
  namespace: knative-eventing
spec:
  signerKeyRef:
    name: natz-operator-operator-private-key
    namespace: default
  privateKey:
    name: typhoon-account-private-key
    namespace: knative-eventing
  signingKeys:
    - name: typhoon-account-signing-key
      namespace: knative-eventing
  imports: []
  exports: []
  limits:
    disk_storage: -1
    streams: -1
    conn: -1
    imports: -1
    exports: -1
    subs: -1
    payload: -1
    data: -1
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-user-private-key
  namespace: knative-eventing
spec:
  type: User
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsUser
metadata:
  name: typhoon
  namespace: knative-eventing
spec:
  accountRef:
    name: typhoon
    namespace: knative-eventing
  privateKey:
    name: typhoon-user-private-key
    namespace: knative-eventing
  signerKeyRef:
    name: typhoon-account-private-key
  limits:
    payload: -1
    subs: -1
    data: -1