apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-account-private-key
  namespace: knative-eventing
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-account-signing-key
  namespace: knative-eventing
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsAccount
metadata:
  name: typhoon
  namespace: knative-eventing
spec:
  signerKeyRef:
    name: natz-operator-operator-private-key
    namespace: default
  privateKey:
    name: typhoon-account-private-key
    namespace: knative-eventing
  signingKeys:
    - name: typhoon-account-signing-key
      namespace: knative-eventing
  exports:
    - name: account-monitoring-services
      subject: $SYS.REQ.ACCOUNT.*.*
      type: 2
      response_type: Stream
      account_token_position: 4
      description: "Request account specific monitoring services for: SUBSZ, CONNZ, LEAFZ, JSZ and INFO"
      info_url: "https://docs.nats.io/nats-server/configuration/sys_accounts"
    - name: account-monitoring-streams
      subject: $SYS.ACCOUNT.*.>"
      type: 1
      account_token_position: 3
      description: "Account specific monitoring stream"
      info_url: "https://docs.nats.io/nats-server/configuration/sys_accounts"
  limits:
    exports: -1
    imports: -1
    subs: -1
    payload: -1
    data: -1
    conn: -1
    wildcards: true
    disallow_bearer: true
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: typhoon-user-private-key
  namespace: knative-eventing
spec:
  type: User
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsUser
metadata:
  name: typhoon
  namespace: knative-eventing
spec:
  accountRef:
    name: typhoon
    namespace: knative-eventing
  privateKey:
    name: typhoon-user-private-key
    namespace: knative-eventing
  signerKeyRef:
    name: typhoon-account-private-key
  limits:
    payload: -1
    subs: -1
    data: -1