apiVersion: v2
appVersion: 0.1.3
description: A Helm chart for the Typhoon Web application
name: typhoon-web
keywords:
- messaging
- jwt
- auth
version: 0.1.29
sources:
- https://github.com/zeiss/typhoon
home: http://github.com/zeiss/typhoon
