//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/zeiss/typhoon/pkg/apis/common/v1alpha1"
	cloudevents "github.com/zeiss/typhoon/pkg/targets/adapter/cloudevents"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsCredentials) DeepCopyInto(out *CloudEventsCredentials) {
	*out = *in
	in.BasicAuth.DeepCopyInto(&out.BasicAuth)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsCredentials.
func (in *CloudEventsCredentials) DeepCopy() *CloudEventsCredentials {
	if in == nil {
		return nil
	}
	out := new(CloudEventsCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsTarget) DeepCopyInto(out *CloudEventsTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsTarget.
func (in *CloudEventsTarget) DeepCopy() *CloudEventsTarget {
	if in == nil {
		return nil
	}
	out := new(CloudEventsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventsTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsTargetList) DeepCopyInto(out *CloudEventsTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEventsTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsTargetList.
func (in *CloudEventsTargetList) DeepCopy() *CloudEventsTargetList {
	if in == nil {
		return nil
	}
	out := new(CloudEventsTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventsTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventsTargetSpec) DeepCopyInto(out *CloudEventsTargetSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CloudEventsCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventsTargetSpec.
func (in *CloudEventsTargetSpec) DeepCopy() *CloudEventsTargetSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEventsTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogTarget) DeepCopyInto(out *DatadogTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogTarget.
func (in *DatadogTarget) DeepCopy() *DatadogTarget {
	if in == nil {
		return nil
	}
	out := new(DatadogTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogTargetList) DeepCopyInto(out *DatadogTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogTargetList.
func (in *DatadogTargetList) DeepCopy() *DatadogTargetList {
	if in == nil {
		return nil
	}
	out := new(DatadogTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogTargetSpec) DeepCopyInto(out *DatadogTargetSpec) {
	*out = *in
	in.DatadogAPIKey.DeepCopyInto(&out.DatadogAPIKey)
	if in.DatadogSite != nil {
		in, out := &in.DatadogSite, &out.DatadogSite
		*out = new(string)
		**out = **in
	}
	if in.MetricPrefix != nil {
		in, out := &in.MetricPrefix, &out.MetricPrefix
		*out = new(string)
		**out = **in
	}
	if in.EventOptions != nil {
		in, out := &in.EventOptions, &out.EventOptions
		*out = new(EventOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogTargetSpec.
func (in *DatadogTargetSpec) DeepCopy() *DatadogTargetSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventOptions) DeepCopyInto(out *EventOptions) {
	*out = *in
	if in.PayloadPolicy != nil {
		in, out := &in.PayloadPolicy, &out.PayloadPolicy
		*out = new(cloudevents.PayloadPolicy)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventOptions.
func (in *EventOptions) DeepCopy() *EventOptions {
	if in == nil {
		return nil
	}
	out := new(EventOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPBasicAuth) DeepCopyInto(out *HTTPBasicAuth) {
	*out = *in
	in.Password.DeepCopyInto(&out.Password)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPBasicAuth.
func (in *HTTPBasicAuth) DeepCopy() *HTTPBasicAuth {
	if in == nil {
		return nil
	}
	out := new(HTTPBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPEventResponse) DeepCopyInto(out *HTTPEventResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPEventResponse.
func (in *HTTPEventResponse) DeepCopy() *HTTPEventResponse {
	if in == nil {
		return nil
	}
	out := new(HTTPEventResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTarget) DeepCopyInto(out *HTTPTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTarget.
func (in *HTTPTarget) DeepCopy() *HTTPTarget {
	if in == nil {
		return nil
	}
	out := new(HTTPTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTargetList) DeepCopyInto(out *HTTPTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTargetList.
func (in *HTTPTargetList) DeepCopy() *HTTPTargetList {
	if in == nil {
		return nil
	}
	out := new(HTTPTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTargetSpec) DeepCopyInto(out *HTTPTargetSpec) {
	*out = *in
	out.Response = in.Response
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.CACertificate != nil {
		in, out := &in.CACertificate, &out.CACertificate
		*out = new(string)
		**out = **in
	}
	if in.BasicAuthUsername != nil {
		in, out := &in.BasicAuthUsername, &out.BasicAuthUsername
		*out = new(string)
		**out = **in
	}
	in.BasicAuthPassword.DeepCopyInto(&out.BasicAuthPassword)
	if in.OAuthClientID != nil {
		in, out := &in.OAuthClientID, &out.OAuthClientID
		*out = new(string)
		**out = **in
	}
	in.OAuthClientSecret.DeepCopyInto(&out.OAuthClientSecret)
	if in.OAuthTokenURL != nil {
		in, out := &in.OAuthTokenURL, &out.OAuthTokenURL
		*out = new(string)
		**out = **in
	}
	if in.OAuthScopes != nil {
		in, out := &in.OAuthScopes, &out.OAuthScopes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTargetSpec.
func (in *HTTPTargetSpec) DeepCopy() *HTTPTargetSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instrument) DeepCopyInto(out *Instrument) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instrument.
func (in *Instrument) DeepCopy() *Instrument {
	if in == nil {
		return nil
	}
	out := new(Instrument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTarget) DeepCopyInto(out *KafkaTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTarget.
func (in *KafkaTarget) DeepCopy() *KafkaTarget {
	if in == nil {
		return nil
	}
	out := new(KafkaTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTargetAuth) DeepCopyInto(out *KafkaTargetAuth) {
	*out = *in
	if in.Kerberos != nil {
		in, out := &in.Kerberos, &out.Kerberos
		*out = new(KafkaTargetKerberos)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(KafkaTargetTLSAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSEnable != nil {
		in, out := &in.TLSEnable, &out.TLSEnable
		*out = new(bool)
		**out = **in
	}
	if in.SecurityMechanisms != nil {
		in, out := &in.SecurityMechanisms, &out.SecurityMechanisms
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTargetAuth.
func (in *KafkaTargetAuth) DeepCopy() *KafkaTargetAuth {
	if in == nil {
		return nil
	}
	out := new(KafkaTargetAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTargetKerberos) DeepCopyInto(out *KafkaTargetKerberos) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.ConfigPath != nil {
		in, out := &in.ConfigPath, &out.ConfigPath
		*out = new(string)
		**out = **in
	}
	if in.KeytabPath != nil {
		in, out := &in.KeytabPath, &out.KeytabPath
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.Keytab != nil {
		in, out := &in.Keytab, &out.Keytab
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTargetKerberos.
func (in *KafkaTargetKerberos) DeepCopy() *KafkaTargetKerberos {
	if in == nil {
		return nil
	}
	out := new(KafkaTargetKerberos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTargetList) DeepCopyInto(out *KafkaTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTargetList.
func (in *KafkaTargetList) DeepCopy() *KafkaTargetList {
	if in == nil {
		return nil
	}
	out := new(KafkaTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTargetSpec) DeepCopyInto(out *KafkaTargetSpec) {
	*out = *in
	if in.TopicReplicationFactor != nil {
		in, out := &in.TopicReplicationFactor, &out.TopicReplicationFactor
		*out = new(int16)
		**out = **in
	}
	if in.TopicPartitions != nil {
		in, out := &in.TopicPartitions, &out.TopicPartitions
		*out = new(int32)
		**out = **in
	}
	if in.BootstrapServers != nil {
		in, out := &in.BootstrapServers, &out.BootstrapServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(KafkaTargetAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTargetSpec.
func (in *KafkaTargetSpec) DeepCopy() *KafkaTargetSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTargetTLSAuth) DeepCopyInto(out *KafkaTargetTLSAuth) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientCert != nil {
		in, out := &in.ClientCert, &out.ClientCert
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(commonv1alpha1.ValueFromField)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTargetTLSAuth.
func (in *KafkaTargetTLSAuth) DeepCopy() *KafkaTargetTLSAuth {
	if in == nil {
		return nil
	}
	out := new(KafkaTargetTLSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzMetricsConnection) DeepCopyInto(out *LogzMetricsConnection) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzMetricsConnection.
func (in *LogzMetricsConnection) DeepCopy() *LogzMetricsConnection {
	if in == nil {
		return nil
	}
	out := new(LogzMetricsConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzMetricsTarget) DeepCopyInto(out *LogzMetricsTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzMetricsTarget.
func (in *LogzMetricsTarget) DeepCopy() *LogzMetricsTarget {
	if in == nil {
		return nil
	}
	out := new(LogzMetricsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogzMetricsTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzMetricsTargetList) DeepCopyInto(out *LogzMetricsTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogzMetricsTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzMetricsTargetList.
func (in *LogzMetricsTargetList) DeepCopy() *LogzMetricsTargetList {
	if in == nil {
		return nil
	}
	out := new(LogzMetricsTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogzMetricsTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzMetricsTargetSpec) DeepCopyInto(out *LogzMetricsTargetSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.Instruments != nil {
		in, out := &in.Instruments, &out.Instruments
		*out = make([]Instrument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventOptions != nil {
		in, out := &in.EventOptions, &out.EventOptions
		*out = new(EventOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzMetricsTargetSpec.
func (in *LogzMetricsTargetSpec) DeepCopy() *LogzMetricsTargetSpec {
	if in == nil {
		return nil
	}
	out := new(LogzMetricsTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzTarget) DeepCopyInto(out *LogzTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzTarget.
func (in *LogzTarget) DeepCopy() *LogzTarget {
	if in == nil {
		return nil
	}
	out := new(LogzTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogzTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzTargetList) DeepCopyInto(out *LogzTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogzTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzTargetList.
func (in *LogzTargetList) DeepCopy() *LogzTargetList {
	if in == nil {
		return nil
	}
	out := new(LogzTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogzTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogzTargetSpec) DeepCopyInto(out *LogzTargetSpec) {
	*out = *in
	in.ShippingToken.DeepCopyInto(&out.ShippingToken)
	if in.EventOptions != nil {
		in, out := &in.EventOptions, &out.EventOptions
		*out = new(EventOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogzTargetSpec.
func (in *LogzTargetSpec) DeepCopy() *LogzTargetSpec {
	if in == nil {
		return nil
	}
	out := new(LogzTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsTarget) DeepCopyInto(out *NatsTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsTarget.
func (in *NatsTarget) DeepCopy() *NatsTarget {
	if in == nil {
		return nil
	}
	out := new(NatsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsTargetList) DeepCopyInto(out *NatsTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsTargetList.
func (in *NatsTargetList) DeepCopy() *NatsTargetList {
	if in == nil {
		return nil
	}
	out := new(NatsTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsTargetSpec) DeepCopyInto(out *NatsTargetSpec) {
	*out = *in
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsTargetSpec.
func (in *NatsTargetSpec) DeepCopy() *NatsTargetSpec {
	if in == nil {
		return nil
	}
	out := new(NatsTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleFunctionSpecSpec) DeepCopyInto(out *OracleFunctionSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleFunctionSpecSpec.
func (in *OracleFunctionSpecSpec) DeepCopy() *OracleFunctionSpecSpec {
	if in == nil {
		return nil
	}
	out := new(OracleFunctionSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleTarget) DeepCopyInto(out *OracleTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleTarget.
func (in *OracleTarget) DeepCopy() *OracleTarget {
	if in == nil {
		return nil
	}
	out := new(OracleTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OracleTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleTargetList) DeepCopyInto(out *OracleTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OracleTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleTargetList.
func (in *OracleTargetList) DeepCopy() *OracleTargetList {
	if in == nil {
		return nil
	}
	out := new(OracleTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OracleTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleTargetSpec) DeepCopyInto(out *OracleTargetSpec) {
	*out = *in
	in.OracleAPIPrivateKey.DeepCopyInto(&out.OracleAPIPrivateKey)
	in.OracleAPIPrivateKeyPassphrase.DeepCopyInto(&out.OracleAPIPrivateKeyPassphrase)
	in.OracleAPIPrivateKeyFingerprint.DeepCopyInto(&out.OracleAPIPrivateKeyFingerprint)
	if in.OracleFunctionSpec != nil {
		in, out := &in.OracleFunctionSpec, &out.OracleFunctionSpec
		*out = new(OracleFunctionSpecSpec)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleTargetSpec.
func (in *OracleTargetSpec) DeepCopy() *OracleTargetSpec {
	if in == nil {
		return nil
	}
	out := new(OracleTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretValueFromSource) DeepCopyInto(out *SecretValueFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretValueFromSource.
func (in *SecretValueFromSource) DeepCopy() *SecretValueFromSource {
	if in == nil {
		return nil
	}
	out := new(SecretValueFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkTarget) DeepCopyInto(out *SplunkTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkTarget.
func (in *SplunkTarget) DeepCopy() *SplunkTarget {
	if in == nil {
		return nil
	}
	out := new(SplunkTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplunkTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkTargetList) DeepCopyInto(out *SplunkTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SplunkTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkTargetList.
func (in *SplunkTargetList) DeepCopy() *SplunkTargetList {
	if in == nil {
		return nil
	}
	out := new(SplunkTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplunkTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkTargetSpec) DeepCopyInto(out *SplunkTargetSpec) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	in.Token.DeepCopyInto(&out.Token)
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(string)
		**out = **in
	}
	if in.SkipTLSVerify != nil {
		in, out := &in.SkipTLSVerify, &out.SkipTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.AdapterOverrides != nil {
		in, out := &in.AdapterOverrides, &out.AdapterOverrides
		*out = new(commonv1alpha1.AdapterOverrides)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkTargetSpec.
func (in *SplunkTargetSpec) DeepCopy() *SplunkTargetSpec {
	if in == nil {
		return nil
	}
	out := new(SplunkTargetSpec)
	in.DeepCopyInto(out)
	return out
}
