{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typhoon.controller.serviceAccount.name" . }}
  labels:
    {{- include "typhoon.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typhoon.controller.serviceAccount.name" . }}
  labels:
    {{- include "typhoon.controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}