openapi: 3.0.0

info:
  version: 1.0.0
  title: Typhoon API
  description: |
    # Introduction

    The Typhoon API allows you to NATS.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8080

tags:
  - name: System
    description: |-
      These are the NATS.io that are managed by Typhoon.
  - name: Team
  - name: Server

consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
#- "https"
- "http"

paths:
  /version:
    get:
      summary: Returns the current version of the API.
      operationId: version
      tags:
        - Server
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"

  /teams:
    get:
      summary: List all teams
      operationId: listTeam
      tags:
        - Team
      produces:
        - "application/json"
      responses:
        '200':
          description: Successfull response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Team'
                type: array

    post:
      summary: Creates a new team
      operationId: createTeam
      tags:
        - Team
      produces:
        - "application/json"
      requestBody:
        $ref: '#/components/requestBodies/CreateTeam'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
      links:
        GetTeamById:
          operationId: getTeam
          parameters:
            teamId: '$response.body#/id'

  /team/{teamId}:
    get:
      summary: Gets a team by ID
      operation: getTeam
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
  /systems:
    get:
      summary: List all managed systems.
      operationId: listSystems
      tags:
        - System
      description: |-
        Returns a list of managed systems.
      responses:
        '200':
          description: A paginated response of all systems
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Systems"

  /systems/{systemId}:
    get:
      summary: List all managed systems.
      operationId: showSystem
      tags:
        - Systems
      description: |-
        Returns a list of managed systems.
      parameters:
        - name: systemId
          in: path
          required: true
          description: The id of the system to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A paginated response of all systems

definitions:
  schemas:
    createTeamResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

components:
  requestBodies:
    CreateTeam:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Team'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      in: header
      name: api_key
      type: apiKey

  schemas:
    Team:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          x-oapi-codegen-extra-tags:
            gorm: "type:uuid;default:gen_random_uuid()"
        name:
          type: string
        description:
          type: string
        contactEmail:
          type: string
        createdAt:
          type: string
          format: date-time
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"
        deletedAt:
          type: string
          format: date-time
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"


    Version:
      type: object
      required:
        - version
        - date
      properties:
        version:
          type: string
        date:
          type: string
    System:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Systems:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/System"

security:
  - bearer_auth: []
  - api_key: []
